# Generated by Django 5.0.3 on 2024-04-07 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="likes",
            field=models.ManyToManyField(
                related_name="offers_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
